import type { TrendyolProduct } from '@/types/trendyol';

export const MOCK_PRODUCTS: TrendyolProduct[] = [
  {
    id: 1,
    barcode: 'SA-WR-6MM-304',
    title: 'Paslanmaz Çelik Tel Halat 6mm — AISI 304 (1x19)',
    productMainId: 'SA-WR-6MM',
    brandId: 1,
    brandName: 'Stainless Art',
    categoryId: 1,
    categoryName: 'Tel Halat',
    quantity: 150,
    stockCode: 'WR-6MM-304',
    dimensionalWeight: 0.22,
    description: 'AISI 304 kalite paslanmaz çelik tel halat. 6mm çap, 1x19 tel yapısı. İç ve dış mekân kullanımına uygundur. Yük kapasitesi: 2.200 kg.',
    currencyType: 'TRY',
    listPrice: 48.90,
    salePrice: 38.90,
    vatRate: 20,
    images: [
      { url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80' },
    ],
    approved: true,
    archived: false,
  },
  {
    id: 2,
    barcode: 'SA-WR-8MM-316',
    title: 'Paslanmaz Çelik Tel Halat 8mm — AISI 316 Deniz Kalitesi',
    productMainId: 'SA-WR-8MM',
    brandId: 1,
    brandName: 'Stainless Art',
    categoryId: 1,
    categoryName: 'Tel Halat',
    quantity: 80,
    stockCode: 'WR-8MM-316',
    dimensionalWeight: 0.39,
    description: 'AISI 316 deniz kalitesi paslanmaz çelik tel halat. 8mm çap, 7x7 tel yapısı. Tuzlu su ve kimyasal ortamlara karşı üstün direnç. Yük kapasitesi: 3.800 kg.',
    currencyType: 'TRY',
    listPrice: 89.90,
    salePrice: 74.90,
    vatRate: 20,
    images: [
      { url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&q=80' },
    ],
    approved: true,
    archived: false,
  },
  {
    id: 3,
    barcode: 'SA-CLIP-6MM-DIN741',
    title: 'Tel Halat Klipsi 6mm — DIN 741 Paslanmaz Çelik',
    productMainId: 'SA-CLIP-6MM',
    brandId: 1,
    brandName: 'Stainless Art',
    categoryId: 2,
    categoryName: 'Bağlantı Elemanları',
    quantity: 500,
    stockCode: 'CLIP-6MM-DIN741',
    dimensionalWeight: 0.05,
    description: 'DIN 741 standartlarında 6mm tel halat için paslanmaz çelik U-bolt klips. AISI 304. Min. eğilme dayanımı 2.100 N.',
    currencyType: 'TRY',
    listPrice: 12.90,
    salePrice: 9.90,
    vatRate: 20,
    images: [
      { url: 'https://images.unsplash.com/photo-1581092335397-9583eb92d232?w=800&q=80' },
    ],
    approved: true,
    archived: false,
  },
  {
    id: 4,
    barcode: 'SA-THIMBLE-8MM-304',
    title: 'Tel Halat Gözlüğü 8mm — Paslanmaz Çelik DIN 6899',
    productMainId: 'SA-THIMBLE-8MM',
    brandId: 1,
    brandName: 'Stainless Art',
    categoryId: 2,
    categoryName: 'Bağlantı Elemanları',
    quantity: 320,
    stockCode: 'THIMBLE-8MM-304',
    dimensionalWeight: 0.04,
    description: 'DIN 6899 B tipi 8mm tel halat gözlüğü. AISI 304 paslanmaz çelik. Halatın uç kısmını korur ve yük dağılımını optimize eder.',
    currencyType: 'TRY',
    listPrice: 18.50,
    salePrice: 18.50,
    vatRate: 20,
    images: [
      { url: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80' },
    ],
    approved: true,
    archived: false,
  },
  {
    id: 5,
    barcode: 'SA-TURNBUCKLE-M12-316',
    title: 'Gergi Vidası M12 — Kapalı Tip AISI 316',
    productMainId: 'SA-TURNBUCKLE-M12',
    brandId: 1,
    brandName: 'Stainless Art',
    categoryId: 2,
    categoryName: 'Bağlantı Elemanları',
    quantity: 45,
    stockCode: 'TURNBUCKLE-M12-316',
    dimensionalWeight: 0.28,
    description: 'M12 kapalı tip gergi vidası. AISI 316 deniz kalitesi paslanmaz çelik. Gerilim kapasitesi: 4.200 kg. İnşaat, marina ve mimari uygulamalar için.',
    currencyType: 'TRY',
    listPrice: 145.00,
    salePrice: 119.90,
    vatRate: 20,
    images: [
      { url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80' },
    ],
    approved: true,
    archived: false,
  },
  {
    id: 6,
    barcode: 'SA-WR-10MM-304-7X7',
    title: 'Paslanmaz Çelik Tel Halat 10mm — 7×7 Esnek Tip',
    productMainId: 'SA-WR-10MM',
    brandId: 1,
    brandName: 'Stainless Art',
    categoryId: 1,
    categoryName: 'Tel Halat',
    quantity: 0,
    stockCode: 'WR-10MM-304-7X7',
    dimensionalWeight: 0.62,
    description: 'AISI 304 esnek tip tel halat. 10mm çap, 7x7 tel yapısı. Yüksek esneklik gerektiren uygulamalar için ideal. Yük kapasitesi: 5.900 kg.',
    currencyType: 'TRY',
    listPrice: 94.90,
    salePrice: 94.90,
    vatRate: 20,
    images: [
      { url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&q=80' },
    ],
    approved: true,
    archived: false,
  },
  {
    id: 7,
    barcode: 'SA-SWAGE-6MM-EYE-316',
    title: 'Sıkıştırmalı Gözlük Terminal 6mm — AISI 316',
    productMainId: 'SA-SWAGE-6MM',
    brandId: 1,
    brandName: 'Stainless Art',
    categoryId: 2,
    categoryName: 'Bağlantı Elemanları',
    quantity: 200,
    stockCode: 'SWAGE-6MM-EYE-316',
    dimensionalWeight: 0.08,
    description: 'Hidrolik baskılı sıkıştırmalı gözlük terminal. 6mm tel halat için. AISI 316 deniz kalitesi. Kayma dayanımı: %100 halat kapasitesi.',
    currencyType: 'TRY',
    listPrice: 67.00,
    salePrice: 54.90,
    vatRate: 20,
    images: [
      { url: 'https://images.unsplash.com/photo-1581092335397-9583eb92d232?w=800&q=80' },
    ],
    approved: true,
    archived: false,
  },
  {
    id: 8,
    barcode: 'SA-SHACKLE-M10-316',
    title: 'Kilit Manşon M10 — Bow Tipi AISI 316',
    productMainId: 'SA-SHACKLE-M10',
    brandId: 1,
    brandName: 'Stainless Art',
    categoryId: 2,
    categoryName: 'Bağlantı Elemanları',
    quantity: 175,
    stockCode: 'SHACKLE-M10-316',
    dimensionalWeight: 0.12,
    description: 'M10 bow tipi kilit manşon. AISI 316 paslanmaz çelik. WLL 1.000 kg. Deniz, inşaat ve endüstriyel kaldırma işlemleri için.',
    currencyType: 'TRY',
    listPrice: 38.50,
    salePrice: 32.90,
    vatRate: 20,
    images: [
      { url: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80' },
    ],
    approved: true,
    archived: false,
  },
];
